plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "/Users/nialomia/.bob/playground/takeoff/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm build"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]